---

- name: 'Download alacritty {{ alacritty.git_url }}'
  git: 
    repo: '{{ alacritty.git_url | default ("https://github.com/alacritty/alacritty.git") }}'
    dest: /tmp/alacritty_repo
    force: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'
  tags: [ alacritty ]

- name: Run alacritty cargo build
  command: cargo build --release
  register: command_result
  args:
    chdir: /tmp/alacritty_repo
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'
  tags: [ alacritty ]

