---
- name: Install package prerequisites
  apt:
    pkg:
    - cmake
    - pkg-config
    - libfreetype6-dev
    - libfontconfig1-dev
    - libxcb-xfixes0-dev
    - python3
  become: true
  tags: [ alacritty ]

- name: 'Download alacritty {{ alacritty.git_url }}'
  git:
    repo: '{{ alacritty.git_url | default ("https://github.com/alacritty/alacritty.git") }}'
    dest: /tmp/alacritty_repo
    force: yes
  tags: [ alacritty ]

- name: Expand cargo_location
  command: echo {{ ansible_env.CARGO_HOME | default("~/.cargo") }}
  register: command_result
  tags: [ alacritty ]

- name: Set expanded cargo_location variable
  set_fact:
    cargo_location_expanded: '{{ command_result.stdout }}'
  tags: [ alacritty ]

- name: Run alacritty cargo build
  command: '{{ cargo_location_expanded }}/bin/cargo build --release'
  register: command_result
  args:
    chdir: /tmp/alacritty_repo
  tags: [ alacritty ]

- name:  Copy Alacritty binary into place
  ansible.builtin.copy:
    src: /tmp/alacritty_repo/release/alacritty
    remote_src: True
    dest:  /usr/local/bin
    owner: root
    group: root
    mode: u+rwx,g+rx,o+rx
  become: True
  tags: [ alacritty ]

- name:  Copy Alacritty svg into place
  ansible.builtin.copy:
    src: /tmp/alacritty_repo/extra/logo/alacritty-term.svg
    remote_src: True
    dest:  /usr/share/pixmaps/Alacritty.svg
    owner: root
    group: root
    mode: u+rw,g+r,o+r
  become: True
  tags: [ alacritty ]

- name: Run alacritty desktop add
  command:  desktop-file-install extra/linux/Alacritty.desktop
  args:
    chdir: /tmp/alacritty_repo
  tags: [ alacritty ]
  become: True

- name: Run desktop database update
  command:  update-desktop-database
  become: True
  tags: [ alacritty ]
