---
# Install & Configure dotfiles

- name: Ensure the requested shell is installed
  apt:
    package:
      - '{{ dotfiles_shell }}'
  become: true
  when: ansible_pkg_mgr == 'apt'
  tags: [ dotfiles ]

- name: Set the default shell as requested
  command: chsh --shell /bin/{{ dotfiles_shell }} {{ ansible_env.USER }}
  register: chsh_check
  failed_when: chsh_check.rc > 0
  changed_when: chsh_check.rc == 0
  become: true
  tags: [ dotfiles ]

- name: 'Download users dotfiles {{ dotfiles_git_url }}'
  git: 
    repo: '{{ dotfiles_git_url | default ("https://github.com/rickprice/dotfiles.git") }}'
    dest: ~/.dotfiles
    force: no
  tags: [ dotfiles ]

- name: Run the dotfiles setup
  command: ~/.dotfiles/setup.sh
  register: dotfiles_check
  failed_when: dotfiles_check.rc > 0
  changed_when: dotfiles_check.rc == 0
  tags: [ dotfiles ]

