---
- name: Add NeoVim PPA (I'm using unstable to get newest NeoVim)
  ansible.builtin.apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
    state: present
    filename: neovim
  when: ansible_pkg_mgr == 'apt'
  tags: [ neovim ]

- name: Install NeoVim
  apt:
    pkg:
    - neovim
  become: yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ neovim ]

# I personally like to use Neovim for everything instead of Vi*, YMMV
- name: Use Neovim as vi
  alternatives:
    name: vi
    path: /usr/bin/nvim
    priority: 60
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'
  
  # This one breaks sometimes
# - name: Use Neovim as vim
#   alternatives:
#     name: vim
#     path: /usr/bin/nvim
#     priority: 60
#   when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'
  
- name: Use Neovim as editor
  alternatives:
    name: editor
    path: /usr/bin/nvim
    priority: 60
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'
  
- name: Use Neovim as view
  alternatives:
    name: view
    path: /usr/bin/nvim
    priority: 60
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'
