---
# Install & Configure EncFS

- name: Add encfs repository
  apt_repository: repo="{{ encfs_ppa }}" state=present

- name: Add public key
  apt_key: keyserver="{{ encfs_ppa_keyserver }}" id="{{ encfs_ppa_id }}" state=present

- name: Update package manager
  apt: update_cache=yes

- name: Install latest encfs package
  apt: pkg="{{ item }}" state=latest force=yes
  with_items:
    - encfs
    - gnome-encfs-manager