---
# Install & Configure Ruby

- name: Install latest ruby package
  state: present
  force: yes
  pkg:
    - ruby
    - ruby-dev
    - rubygems
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: [ ruby ]
 
# Install Ruby Gems
- include_tasks: ruby_gems.yml
