---
# Install & Configure Ruby

- name: Install latest ruby package
  apt: pkg="{{ item }}" state=present force=yes
  with_items:
    - ruby
    - ruby-dev
    - rubygems
  sudo: true

# Install Ruby Gems

- include_tasks: ruby_gems.yml