---
# Install & Configure Ruby Gems

- name: Install Ruby Gems for NeoVim
  community.general.gem:
    name: neovim
    state: present

- name: Install Ruby Gems
  community.general.gem:
    with_items: "{{ ruby_gems | default([]) }}"
    state: present
