---
# Install & Configure Ruby Gems

- name: Install Ruby Gems for NeoVim
  community.general.gem:
    name: neovim
    state: present
  become: false

- name: Install configured gems.
  gem:
    name: "{{ item }}"
    state: present
  become: false
  with_items: "{{ ruby_gems | default([]) }}"
