---

- name: Install python
  apt:
    pkg:
    - python3
    - python3-pip
    - python
    - python-pip
  become: yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ python ]

# Install Pip packages

- include: pip2.yml
- include: pip3.yml
