---

- name: Install python
  apt: pkg="{{ item }}" state=present force=yes
  with_items:
    - python3
    - python3-pip
    - python
    - python-pip
  become: true

# Install Pip packages

- include: pip2.yml
- include: pip3.yml
