---

- name: Install python
  apt:
    pkg:
    - python3
    - python3-pip
    - python-is-python3
# I don't want to use Python2
#    - python
#    - python-pip
  become: yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ python ]

- name: Install python packages I care a lot about
  apt:
    pkg:
    - flake8
    - black
    - mypy
    - mypy-doc
    - python-black-doc
    - python3-pynvim
    - python3-venv
  become: yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ python ]

# Install Pip packages

# I don't want to use Python2
#- include: pip2.yml
- include: pip3.yml
