---
- name: Install package prerequisites
  apt:
    pkg:
    - lib32z1
  become: true
  tags: [ printer ]

- name: Install package prerequisites for Ansible
  pip:
    name: pexpect
  become: true
  tags: [ printer ]

- name: Create directory if it does not exist
  ansible.builtin.file:
    path: /tmp/PrinterInstall
    state: directory
    mode: '0755'

- name: Download Printer Drivers
  ansible.builtin.get_url:
    url: https://download.brother.com/welcome/dlf006893/linux-brprinter-installer-2.2.2-2.gz
    dest: /tmp/PrinterInstall/linux-printer-installer.gz
  tags: [ printer ]

- name: Gunzip Printer Driver Script
  command: gunzip /tmp/PrinterInstall/linux-printer-installer.gz
  args:
    creates: /tmp/PrinterInstall/linux-printer-installer
  tags: [ printer ]

- name: Make Printer Driver Script Executable
  ansible.builtin.file:
    dest: /tmp/PrinterInstall/linux-printer-installer
    mode: a+x
  tags: [ printer ]

- name: Install Printer Drivers using script
  ansible.builtin.expect:
    command: /tmp/PrinterInstall/linux-printer-installer
    responses:
      'Input model name ->': 'MFC-L2700DW'
      'OK\? \[y/N\] ->': 'y'
      'Will you specify the Device URI? \[y/N\] ->': 'y'
      'select the number of the destination Device URI. ->': 'I'
      'enter IP Address ->': '192.168.0.194'
      'Test Print? \[y/N\] ->': 'n'
      'Hit Enter/Return key.': ''
      'Do you agree? \[Y/n\] ->': 'y'
    timeout: 180
  when: ansible_pkg_mgr == 'apt'
  tags: [ printer ]
