---
# Install & Configure Dropbox

- name: Check if dropbox is installed
  command: dpkg-query -W dropbox
  register: dropbox_check_deb
  failed_when: dropbox_check_deb.rc > 1
  changed_when: dropbox_check_deb.rc == 1

- name: Install dropbox
  apt: deb="{{ dropbox_url }}"
  become: true
  when: dropbox_check_deb.rc == 1