---
# Install & Configure Spotify

- name: Add Spotify repository
  apt_repository: 
    repo: "{{ spotify_ppa }}" 
    state: present
  become: true

- name: Add Spotify public key
  apt_key: 
    keyserver: "{{ spotify_ppa_keyserver }}"
    id: "{{ spotify_ppa_id }}" 
    state: present
  become: true

- name: Update packages
  apt: 
    update_cache: yes
  become: true

- name: Install latest Spotify package
  apt: 
    pkg:
    - spotify-client
  become: true
  state: latest
  force: yes
