---
# Install & Configure Chromium

- name: Install latest chromium package with codecs
  apt: pkg="{{ item }}" state=present force=yes
  with_items:
    - chromium-browser
    - chromium-browser-l10n
    - chromium-codecs-ffmpeg-extra
  become: true

- name: Check if ~/.profile exists
  stat:
    path: "{{ ansible_env.HOME }}/.profile"
  register: user_profile
 
- name: Export CHROME_BIN chrome executable
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.profile"
    regexp: "CHROME_BIN"
    line: "export CHROME_BIN=/usr/bin/chromium-browser"
    state: present
  when: user_profile.stat.exists
