---
# Install & Configure Common Tools

- name: Install common tools
  apt:
    update_cache: yes
    pkg: "{{ apt_packages | default([]) }}"
  become: true
  when: ansible_pkg_mgr == 'apt'
  tags: [ packages ]
