---
# Install & Configure Common Tools
  tasks:
    - name: Printing all the environment variables in Ansible
      debug:
        msg: "apt_packages is: {{ apt_packages }}"
      become_user: root
      become: true

- name: Install common tools
  apt:
    update_cache: yes
    pkg: "{{ apt_packages | default([]) }}"
  become: true
  when: ansible_pkg_mgr == 'apt'
  tags: [ packages ]
