---

- name: Install Perl
  apt:
    pkg:
    - perl
  become: yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ perl ]

- name: Install Perl packages I care a lot about
  apt:
    pkg:
    - libcode-tidyall-perl
    - libdbd-pg-perl
    - cpanminus
    - libio-aio-perl
  become: yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ perl ]

- name: Install Perl::LanguageServer
  community.general.cpanm:
    name: Perl::LanguageServer
    system_lib: True
    installdeps: True
  become: true
  tags: [ perl ]

- name: Install Neovim::Ext
  community.general.cpanm:
    name: Neovim::Ext
    system_lib: True
    installdeps: True
  become: true
  tags: [ perl ]

- name: Install local::lib
  community.general.cpanm:
    name: local::lib
    installdeps: True
    system_lib: True
  become: true
  tags: [ perl ]
